preprocess:
  sequence_epochs:      20
  big_group_size:       40
  enhance_window_stride: 10

train:
  kernel_size: 3
  epochs: 60
  batch_size: 8
  learning_rate: 0.001  # 添加这一行
  u_depths: [4, 4, 4, 4]
  u_inner_filter: 256  # 原值为8，调整为与最终通道数匹配
  filters: [16, 32, 64, 128, 256]
  mse_filters: [16, 32, 64, 128, 256] 
  pooling_sizes: [5, 4, 3, 2] 
  dilation_sizes: [1, 2, 3, 4]

evaluation:
  label_class: ["W", "N1", "N2", "N3", "REM"]

class_weights: [1.0, 1.80, 1.0, 1.25, 1.20]
patience: 5
optimizer: "adam"
sleep_epoch_len: 3000
