data:
  data_dir: "./data/"

preprocess:
  sequence_epochs: 20  # 每个样本包含20个连续的30秒片段
  enhance_window_stride: 5  # 数据增强时的滑动窗口步长
  normalize: true

model:
  time_steps: 3000  # 固定时间步长
  hidden_dim: 64  # 隐藏层维度
  num_classes: 5  # 五分类
  num_blocks: 2  # Conbimamba块的数量

training:
  batch_size: 8
  epochs: 50
  lr: 0.001
  patience: 10  # 早停参数
  k_folds: 10  # K折交叉验证数量